version: '3.8'

services:
   app-prod:
      container_name: todoappserver-prod
      image: todoappserver-prod:latest
      build:
        context: .
        dockerfile: Dockerfile.prod
      env_file:
        - .env
      ports:
        - '9000:9000'
      profiles:
        - prod
volumes:
  db-data:
      